/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileNameIndexImport } from './routes/profile/$name/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileNameIndexRoute = ProfileNameIndexImport.update({
  id: '/profile/$name/',
  path: '/profile/$name/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$name/': {
      id: '/profile/$name/'
      path: '/profile/$name'
      fullPath: '/profile/$name'
      preLoaderRoute: typeof ProfileNameIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$name': typeof ProfileNameIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$name': typeof ProfileNameIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile/$name/': typeof ProfileNameIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile/$name'
  id: '__root__' | '/' | '/profile/$name/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileNameIndexRoute: typeof ProfileNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileNameIndexRoute: ProfileNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile/$name/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile/$name/": {
      "filePath": "profile/$name/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
