/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NameIndexRouteImport } from './routes/$name/index'
import { Route as NameRecordsRouteImport } from './routes/$name/records'

const NameIndexRoute = NameIndexRouteImport.update({
  id: '/$name/',
  path: '/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRecordsRoute = NameRecordsRouteImport.update({
  id: '/$name/records',
  path: '/$name/records',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$name/records': typeof NameRecordsRoute
  '/$name': typeof NameIndexRoute
}
export interface FileRoutesByTo {
  '/$name/records': typeof NameRecordsRoute
  '/$name': typeof NameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$name/records': typeof NameRecordsRoute
  '/$name/': typeof NameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$name/records' | '/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/$name/records' | '/$name'
  id: '__root__' | '/$name/records' | '/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NameRecordsRoute: typeof NameRecordsRoute
  NameIndexRoute: typeof NameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$name/': {
      id: '/$name/'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/records': {
      id: '/$name/records'
      path: '/$name/records'
      fullPath: '/$name/records'
      preLoaderRoute: typeof NameRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  NameRecordsRoute: NameRecordsRoute,
  NameIndexRoute: NameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
