/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NameIndexRouteImport } from './routes/$name/index'
import { Route as AddrAddrRouteImport } from './routes/addr/$addr'
import { Route as NameTokenRouteImport } from './routes/$name/token'
import { Route as NameResolverRouteImport } from './routes/$name/resolver'
import { Route as NameRegistryRouteImport } from './routes/$name/registry'
import { Route as NameRecordsRouteImport } from './routes/$name/records'
import { Route as NameOwnershipRouteImport } from './routes/$name/ownership'
import { Route as NameHistoryRouteImport } from './routes/$name/history'
import { Route as NameEditRecordsRouteImport } from './routes/$name/edit-records'
import { Route as NameDeployRegistryRouteImport } from './routes/$name/deploy-registry'
import { Route as AddrAddrIndexRouteImport } from './routes/addr/$addr/index'
import { Route as NameRolesIndexRouteImport } from './routes/$name/roles/index'
import { Route as AddrAddrReverseResolutionRouteImport } from './routes/addr/$addr/reverse-resolution'
import { Route as AddrAddrResolutionRouteImport } from './routes/addr/$addr/resolution'
import { Route as AddrAddrNamesRouteImport } from './routes/addr/$addr/names'
import { Route as AddrAddrHistoryRouteImport } from './routes/addr/$addr/history'
import { Route as NameRolesAddUserRouteImport } from './routes/$name/roles/add-user'

const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NameIndexRoute = NameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NameRoute,
} as any)
const AddrAddrRoute = AddrAddrRouteImport.update({
  id: '/addr/$addr',
  path: '/addr/$addr',
  getParentRoute: () => rootRouteImport,
} as any)
const NameTokenRoute = NameTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => NameRoute,
} as any)
const NameResolverRoute = NameResolverRouteImport.update({
  id: '/resolver',
  path: '/resolver',
  getParentRoute: () => NameRoute,
} as any)
const NameRegistryRoute = NameRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => NameRoute,
} as any)
const NameRecordsRoute = NameRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => NameRoute,
} as any)
const NameOwnershipRoute = NameOwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => NameRoute,
} as any)
const NameHistoryRoute = NameHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => NameRoute,
} as any)
const NameEditRecordsRoute = NameEditRecordsRouteImport.update({
  id: '/edit-records',
  path: '/edit-records',
  getParentRoute: () => NameRoute,
} as any)
const NameDeployRegistryRoute = NameDeployRegistryRouteImport.update({
  id: '/deploy-registry',
  path: '/deploy-registry',
  getParentRoute: () => NameRoute,
} as any)
const AddrAddrIndexRoute = AddrAddrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddrAddrRoute,
} as any)
const NameRolesIndexRoute = NameRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => NameRoute,
} as any)
const AddrAddrReverseResolutionRoute =
  AddrAddrReverseResolutionRouteImport.update({
    id: '/reverse-resolution',
    path: '/reverse-resolution',
    getParentRoute: () => AddrAddrRoute,
  } as any)
const AddrAddrResolutionRoute = AddrAddrResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => AddrAddrRoute,
} as any)
const AddrAddrNamesRoute = AddrAddrNamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => AddrAddrRoute,
} as any)
const AddrAddrHistoryRoute = AddrAddrHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AddrAddrRoute,
} as any)
const NameRolesAddUserRoute = NameRolesAddUserRouteImport.update({
  id: '/roles/add-user',
  path: '/roles/add-user',
  getParentRoute: () => NameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRouteWithChildren
  '/$name/deploy-registry': typeof NameDeployRegistryRoute
  '/$name/edit-records': typeof NameEditRecordsRoute
  '/$name/history': typeof NameHistoryRoute
  '/$name/ownership': typeof NameOwnershipRoute
  '/$name/records': typeof NameRecordsRoute
  '/$name/registry': typeof NameRegistryRoute
  '/$name/resolver': typeof NameResolverRoute
  '/$name/token': typeof NameTokenRoute
  '/addr/$addr': typeof AddrAddrRouteWithChildren
  '/$name/': typeof NameIndexRoute
  '/$name/roles/add-user': typeof NameRolesAddUserRoute
  '/addr/$addr/history': typeof AddrAddrHistoryRoute
  '/addr/$addr/names': typeof AddrAddrNamesRoute
  '/addr/$addr/resolution': typeof AddrAddrResolutionRoute
  '/addr/$addr/reverse-resolution': typeof AddrAddrReverseResolutionRoute
  '/$name/roles': typeof NameRolesIndexRoute
  '/addr/$addr/': typeof AddrAddrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name/deploy-registry': typeof NameDeployRegistryRoute
  '/$name/edit-records': typeof NameEditRecordsRoute
  '/$name/history': typeof NameHistoryRoute
  '/$name/ownership': typeof NameOwnershipRoute
  '/$name/records': typeof NameRecordsRoute
  '/$name/registry': typeof NameRegistryRoute
  '/$name/resolver': typeof NameResolverRoute
  '/$name/token': typeof NameTokenRoute
  '/$name': typeof NameIndexRoute
  '/$name/roles/add-user': typeof NameRolesAddUserRoute
  '/addr/$addr/history': typeof AddrAddrHistoryRoute
  '/addr/$addr/names': typeof AddrAddrNamesRoute
  '/addr/$addr/resolution': typeof AddrAddrResolutionRoute
  '/addr/$addr/reverse-resolution': typeof AddrAddrReverseResolutionRoute
  '/$name/roles': typeof NameRolesIndexRoute
  '/addr/$addr': typeof AddrAddrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRouteWithChildren
  '/$name/deploy-registry': typeof NameDeployRegistryRoute
  '/$name/edit-records': typeof NameEditRecordsRoute
  '/$name/history': typeof NameHistoryRoute
  '/$name/ownership': typeof NameOwnershipRoute
  '/$name/records': typeof NameRecordsRoute
  '/$name/registry': typeof NameRegistryRoute
  '/$name/resolver': typeof NameResolverRoute
  '/$name/token': typeof NameTokenRoute
  '/addr/$addr': typeof AddrAddrRouteWithChildren
  '/$name/': typeof NameIndexRoute
  '/$name/roles/add-user': typeof NameRolesAddUserRoute
  '/addr/$addr/history': typeof AddrAddrHistoryRoute
  '/addr/$addr/names': typeof AddrAddrNamesRoute
  '/addr/$addr/resolution': typeof AddrAddrResolutionRoute
  '/addr/$addr/reverse-resolution': typeof AddrAddrReverseResolutionRoute
  '/$name/roles/': typeof NameRolesIndexRoute
  '/addr/$addr/': typeof AddrAddrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/$name/deploy-registry'
    | '/$name/edit-records'
    | '/$name/history'
    | '/$name/ownership'
    | '/$name/records'
    | '/$name/registry'
    | '/$name/resolver'
    | '/$name/token'
    | '/addr/$addr'
    | '/$name/'
    | '/$name/roles/add-user'
    | '/addr/$addr/history'
    | '/addr/$addr/names'
    | '/addr/$addr/resolution'
    | '/addr/$addr/reverse-resolution'
    | '/$name/roles'
    | '/addr/$addr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$name/deploy-registry'
    | '/$name/edit-records'
    | '/$name/history'
    | '/$name/ownership'
    | '/$name/records'
    | '/$name/registry'
    | '/$name/resolver'
    | '/$name/token'
    | '/$name'
    | '/$name/roles/add-user'
    | '/addr/$addr/history'
    | '/addr/$addr/names'
    | '/addr/$addr/resolution'
    | '/addr/$addr/reverse-resolution'
    | '/$name/roles'
    | '/addr/$addr'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/$name/deploy-registry'
    | '/$name/edit-records'
    | '/$name/history'
    | '/$name/ownership'
    | '/$name/records'
    | '/$name/registry'
    | '/$name/resolver'
    | '/$name/token'
    | '/addr/$addr'
    | '/$name/'
    | '/$name/roles/add-user'
    | '/addr/$addr/history'
    | '/addr/$addr/names'
    | '/addr/$addr/resolution'
    | '/addr/$addr/reverse-resolution'
    | '/$name/roles/'
    | '/addr/$addr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRouteWithChildren
  AddrAddrRoute: typeof AddrAddrRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/': {
      id: '/$name/'
      path: '/'
      fullPath: '/$name/'
      preLoaderRoute: typeof NameIndexRouteImport
      parentRoute: typeof NameRoute
    }
    '/addr/$addr': {
      id: '/addr/$addr'
      path: '/addr/$addr'
      fullPath: '/addr/$addr'
      preLoaderRoute: typeof AddrAddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/token': {
      id: '/$name/token'
      path: '/token'
      fullPath: '/$name/token'
      preLoaderRoute: typeof NameTokenRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/resolver': {
      id: '/$name/resolver'
      path: '/resolver'
      fullPath: '/$name/resolver'
      preLoaderRoute: typeof NameResolverRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/registry': {
      id: '/$name/registry'
      path: '/registry'
      fullPath: '/$name/registry'
      preLoaderRoute: typeof NameRegistryRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/records': {
      id: '/$name/records'
      path: '/records'
      fullPath: '/$name/records'
      preLoaderRoute: typeof NameRecordsRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/ownership': {
      id: '/$name/ownership'
      path: '/ownership'
      fullPath: '/$name/ownership'
      preLoaderRoute: typeof NameOwnershipRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/history': {
      id: '/$name/history'
      path: '/history'
      fullPath: '/$name/history'
      preLoaderRoute: typeof NameHistoryRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/edit-records': {
      id: '/$name/edit-records'
      path: '/edit-records'
      fullPath: '/$name/edit-records'
      preLoaderRoute: typeof NameEditRecordsRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/deploy-registry': {
      id: '/$name/deploy-registry'
      path: '/deploy-registry'
      fullPath: '/$name/deploy-registry'
      preLoaderRoute: typeof NameDeployRegistryRouteImport
      parentRoute: typeof NameRoute
    }
    '/addr/$addr/': {
      id: '/addr/$addr/'
      path: '/'
      fullPath: '/addr/$addr/'
      preLoaderRoute: typeof AddrAddrIndexRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/$name/roles/': {
      id: '/$name/roles/'
      path: '/roles'
      fullPath: '/$name/roles'
      preLoaderRoute: typeof NameRolesIndexRouteImport
      parentRoute: typeof NameRoute
    }
    '/addr/$addr/reverse-resolution': {
      id: '/addr/$addr/reverse-resolution'
      path: '/reverse-resolution'
      fullPath: '/addr/$addr/reverse-resolution'
      preLoaderRoute: typeof AddrAddrReverseResolutionRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/addr/$addr/resolution': {
      id: '/addr/$addr/resolution'
      path: '/resolution'
      fullPath: '/addr/$addr/resolution'
      preLoaderRoute: typeof AddrAddrResolutionRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/addr/$addr/names': {
      id: '/addr/$addr/names'
      path: '/names'
      fullPath: '/addr/$addr/names'
      preLoaderRoute: typeof AddrAddrNamesRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/addr/$addr/history': {
      id: '/addr/$addr/history'
      path: '/history'
      fullPath: '/addr/$addr/history'
      preLoaderRoute: typeof AddrAddrHistoryRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/$name/roles/add-user': {
      id: '/$name/roles/add-user'
      path: '/roles/add-user'
      fullPath: '/$name/roles/add-user'
      preLoaderRoute: typeof NameRolesAddUserRouteImport
      parentRoute: typeof NameRoute
    }
  }
}

interface NameRouteChildren {
  NameDeployRegistryRoute: typeof NameDeployRegistryRoute
  NameEditRecordsRoute: typeof NameEditRecordsRoute
  NameHistoryRoute: typeof NameHistoryRoute
  NameOwnershipRoute: typeof NameOwnershipRoute
  NameRecordsRoute: typeof NameRecordsRoute
  NameRegistryRoute: typeof NameRegistryRoute
  NameResolverRoute: typeof NameResolverRoute
  NameTokenRoute: typeof NameTokenRoute
  NameIndexRoute: typeof NameIndexRoute
  NameRolesAddUserRoute: typeof NameRolesAddUserRoute
  NameRolesIndexRoute: typeof NameRolesIndexRoute
}

const NameRouteChildren: NameRouteChildren = {
  NameDeployRegistryRoute: NameDeployRegistryRoute,
  NameEditRecordsRoute: NameEditRecordsRoute,
  NameHistoryRoute: NameHistoryRoute,
  NameOwnershipRoute: NameOwnershipRoute,
  NameRecordsRoute: NameRecordsRoute,
  NameRegistryRoute: NameRegistryRoute,
  NameResolverRoute: NameResolverRoute,
  NameTokenRoute: NameTokenRoute,
  NameIndexRoute: NameIndexRoute,
  NameRolesAddUserRoute: NameRolesAddUserRoute,
  NameRolesIndexRoute: NameRolesIndexRoute,
}

const NameRouteWithChildren = NameRoute._addFileChildren(NameRouteChildren)

interface AddrAddrRouteChildren {
  AddrAddrHistoryRoute: typeof AddrAddrHistoryRoute
  AddrAddrNamesRoute: typeof AddrAddrNamesRoute
  AddrAddrResolutionRoute: typeof AddrAddrResolutionRoute
  AddrAddrReverseResolutionRoute: typeof AddrAddrReverseResolutionRoute
  AddrAddrIndexRoute: typeof AddrAddrIndexRoute
}

const AddrAddrRouteChildren: AddrAddrRouteChildren = {
  AddrAddrHistoryRoute: AddrAddrHistoryRoute,
  AddrAddrNamesRoute: AddrAddrNamesRoute,
  AddrAddrResolutionRoute: AddrAddrResolutionRoute,
  AddrAddrReverseResolutionRoute: AddrAddrReverseResolutionRoute,
  AddrAddrIndexRoute: AddrAddrIndexRoute,
}

const AddrAddrRouteWithChildren = AddrAddrRoute._addFileChildren(
  AddrAddrRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRouteWithChildren,
  AddrAddrRoute: AddrAddrRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
