packages:
  - apps/*
  - packages/*
  - workers/*

autoInstallPeers: false

catalog:
  '@ensdomains/ensjs': https://pkg.pr.new/ensdomains/ensjs/@ensdomains/ensjs@2d1d13d
  '@ensdomains/ensjs-abi': https://pkg.pr.new/ensdomains/ensjs/@ensdomains/ensjs-abi@2d1d13d
  xstate: ^5.24.0

dedupeDirectDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@rhinestone/sdk"
  - '@lingui/*'

resolutionMode: highest

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 1440
