packages:
  - apps/*
  - packages/*
  - workers/*

autoInstallPeers: false

catalog:
  "@ensdomains/ensjs": https://pkg.pr.new/ensdomains/ensjs/@ensdomains/ensjs@c560f61
  "@ensdomains/ensjs-abi": https://pkg.pr.new/ensdomains/ensjs/@ensdomains/ensjs-abi@c560f61
  xstate: ^5.24.0
  "@typescript/native-preview": 7.0.0-dev.20260421.2
  vite: ^8.0.10
  vitest: ^4.1.5
  "@cloudflare/vite-plugin": ^1.33.1
  wrangler: ^4.51.0

catalogs:
  typescript6:
    typescript: ^6.0.3

dedupeDirectDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@rhinestone/sdk"
  - "@lingui/*"
  - rolldown
  - "@rolldown/*"

resolutionMode: highest

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 1440
