import { defineConfig } from '@playwright/test'
import { baseConfig } from '../../playwright.config.base.js'

export default defineConfig({
  ...baseConfig,
  testDir: './tests',
  use: {
    ...baseConfig.use,
    baseURL: process.env.PORTAL_APP_URL ?? 'http://localhost:3001',
  },
  projects: [
    /**
     * The fixtures' own self-tests (`e2e-build-goal.md` §6 B2). Runs first and
     * `portal-e2e` depends on it, so a broken fixture aborts the run instead of
     * producing a suite-full of confident wrong results underneath it — which
     * is what happened when `makeV1Name` was writing to a deployment the app
     * never read, for weeks, green the whole time.
     *
     * `testDir` is overridden per-project because the harness spec is shared
     * and lives outside `projects/portal/tests`.
     */
    {
      name: 'harness',
      testDir: '../../specs',
      testMatch: /harness\.spec\.ts$/,
    },
    {
      name: 'portal-e2e',
      testMatch: /.*\.spec\.ts$/, // all tests in the tests directory
      dependencies: ['harness'],
    },
    /**
     * The V1 shape matrix: one cell per (portal tab × way a V1 name can be
     * held). Generated by `scripts/generate-v1-matrix.ts`.
     *
     * Extra projects in *this* config rather than a config of their own,
     * deliberately. `reconcile.ts` asks each config in `PROJECT_CONFIGS` what
     * it runs, with no `--project` filter, so projects added here are counted
     * without touching the reconciler — and a new config file that somebody
     * forgets to register is exactly how three committed migration specs came
     * to be run by nothing and scored zero.
     *
     * `testDir` is a sibling of `./tests`, so `portal-e2e`'s `testMatch` cannot
     * pick the matrix up and slow the default run. Disjoint directories rather
     * than a `testIgnore` — an ignore rule is the other half of that same trap.
     */
    {
      name: 'portal-v1-matrix',
      testDir: './matrix',
      testIgnore: /v1-shapes-time/,
      dependencies: ['harness'],
    },
    /**
     * The shapes that move the fork clock. Forward-only and never undone, so
     * they are quarantined here: run last, never alongside the rest.
     */
    {
      name: 'portal-v1-matrix-time',
      testDir: './matrix',
      testMatch: /v1-shapes-time/,
      dependencies: ['harness'],
    },
  ],
})
