**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc
!patches/
!patches/**

!workers/
!workers/commemorative-nft-generator/
!workers/commemorative-nft-generator/**

workers/commemorative-nft-generator/.env
workers/commemorative-nft-generator/.env.*
!workers/commemorative-nft-generator/.env.example
workers/commemorative-nft-generator/benchmark-output/
workers/commemorative-nft-generator/dist/
workers/commemorative-nft-generator/node_modules/
