/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotificationsRouteRouteImport } from './routes/notifications/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as AutoRenewalIndexRouteImport } from './routes/auto-renewal/index'
import { Route as PaymentListRouteImport } from './routes/payment/list'
import { Route as PaymentAddRouteImport } from './routes/payment/add'
import { Route as LegalTrademarkGuidelinesRouteImport } from './routes/legal/trademark-guidelines'
import { Route as LegalTermsOfUseRouteImport } from './routes/legal/terms-of-use'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as PNameIndexRouteImport } from './routes/p/$name/index'
import { Route as NotificationsSettingsIndexRouteImport } from './routes/notifications/settings/index'
import { Route as DebugBackendIndexRouteImport } from './routes/debug/backend/index'
import { Route as PNameEditRouteImport } from './routes/p/$name/edit'
import { Route as DebugBackendSettingsRouteImport } from './routes/debug/backend/settings'
import { Route as NotificationsChannelsEmailVerifyRouteImport } from './routes/notifications/channels/email/verify'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRouteRoute = NotificationsRouteRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRouteRoute,
} as any)
const AutoRenewalIndexRoute = AutoRenewalIndexRouteImport.update({
  id: '/auto-renewal/',
  path: '/auto-renewal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentListRoute = PaymentListRouteImport.update({
  id: '/payment/list',
  path: '/payment/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentAddRoute = PaymentAddRouteImport.update({
  id: '/payment/add',
  path: '/payment/add',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTrademarkGuidelinesRoute =
  LegalTrademarkGuidelinesRouteImport.update({
    id: '/legal/trademark-guidelines',
    path: '/legal/trademark-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalTermsOfUseRoute = LegalTermsOfUseRouteImport.update({
  id: '/legal/terms-of-use',
  path: '/legal/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PNameIndexRoute = PNameIndexRouteImport.update({
  id: '/p/$name/',
  path: '/p/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsIndexRoute =
  NotificationsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => NotificationsRouteRoute,
  } as any)
const DebugBackendIndexRoute = DebugBackendIndexRouteImport.update({
  id: '/debug/backend/',
  path: '/debug/backend/',
  getParentRoute: () => rootRouteImport,
} as any)
const PNameEditRoute = PNameEditRouteImport.update({
  id: '/p/$name/edit',
  path: '/p/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugBackendSettingsRoute = DebugBackendSettingsRouteImport.update({
  id: '/debug/backend/settings',
  path: '/debug/backend/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsChannelsEmailVerifyRoute =
  NotificationsChannelsEmailVerifyRouteImport.update({
    id: '/channels/email/verify',
    path: '/channels/email/verify',
    getParentRoute: () => NotificationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/legal/trademark-guidelines': typeof LegalTrademarkGuidelinesRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/auto-renewal/': typeof AutoRenewalIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/debug/backend/settings': typeof DebugBackendSettingsRoute
  '/p/$name/edit': typeof PNameEditRoute
  '/debug/backend/': typeof DebugBackendIndexRoute
  '/notifications/settings/': typeof NotificationsSettingsIndexRoute
  '/p/$name/': typeof PNameIndexRoute
  '/notifications/channels/email/verify': typeof NotificationsChannelsEmailVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/legal/trademark-guidelines': typeof LegalTrademarkGuidelinesRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/auto-renewal': typeof AutoRenewalIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/debug/backend/settings': typeof DebugBackendSettingsRoute
  '/p/$name/edit': typeof PNameEditRoute
  '/debug/backend': typeof DebugBackendIndexRoute
  '/notifications/settings': typeof NotificationsSettingsIndexRoute
  '/p/$name': typeof PNameIndexRoute
  '/notifications/channels/email/verify': typeof NotificationsChannelsEmailVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notifications': typeof NotificationsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/legal/trademark-guidelines': typeof LegalTrademarkGuidelinesRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/auto-renewal/': typeof AutoRenewalIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/debug/backend/settings': typeof DebugBackendSettingsRoute
  '/p/$name/edit': typeof PNameEditRoute
  '/debug/backend/': typeof DebugBackendIndexRoute
  '/notifications/settings/': typeof NotificationsSettingsIndexRoute
  '/p/$name/': typeof PNameIndexRoute
  '/notifications/channels/email/verify': typeof NotificationsChannelsEmailVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/dashboard'
    | '/register'
    | '/wallet'
    | '/legal/privacy-policy'
    | '/legal/terms-of-use'
    | '/legal/trademark-guidelines'
    | '/payment/add'
    | '/payment/list'
    | '/auto-renewal/'
    | '/notifications/'
    | '/debug/backend/settings'
    | '/p/$name/edit'
    | '/debug/backend/'
    | '/notifications/settings/'
    | '/p/$name/'
    | '/notifications/channels/email/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/register'
    | '/wallet'
    | '/legal/privacy-policy'
    | '/legal/terms-of-use'
    | '/legal/trademark-guidelines'
    | '/payment/add'
    | '/payment/list'
    | '/auto-renewal'
    | '/notifications'
    | '/debug/backend/settings'
    | '/p/$name/edit'
    | '/debug/backend'
    | '/notifications/settings'
    | '/p/$name'
    | '/notifications/channels/email/verify'
  id:
    | '__root__'
    | '/'
    | '/notifications'
    | '/dashboard'
    | '/register'
    | '/wallet'
    | '/legal/privacy-policy'
    | '/legal/terms-of-use'
    | '/legal/trademark-guidelines'
    | '/payment/add'
    | '/payment/list'
    | '/auto-renewal/'
    | '/notifications/'
    | '/debug/backend/settings'
    | '/p/$name/edit'
    | '/debug/backend/'
    | '/notifications/settings/'
    | '/p/$name/'
    | '/notifications/channels/email/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificationsRouteRoute: typeof NotificationsRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RegisterRoute: typeof RegisterRoute
  WalletRoute: typeof WalletRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfUseRoute: typeof LegalTermsOfUseRoute
  LegalTrademarkGuidelinesRoute: typeof LegalTrademarkGuidelinesRoute
  PaymentAddRoute: typeof PaymentAddRoute
  PaymentListRoute: typeof PaymentListRoute
  AutoRenewalIndexRoute: typeof AutoRenewalIndexRoute
  DebugBackendSettingsRoute: typeof DebugBackendSettingsRoute
  PNameEditRoute: typeof PNameEditRoute
  DebugBackendIndexRoute: typeof DebugBackendIndexRoute
  PNameIndexRoute: typeof PNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRouteRoute
    }
    '/auto-renewal/': {
      id: '/auto-renewal/'
      path: '/auto-renewal'
      fullPath: '/auto-renewal/'
      preLoaderRoute: typeof AutoRenewalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/list': {
      id: '/payment/list'
      path: '/payment/list'
      fullPath: '/payment/list'
      preLoaderRoute: typeof PaymentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/add': {
      id: '/payment/add'
      path: '/payment/add'
      fullPath: '/payment/add'
      preLoaderRoute: typeof PaymentAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/trademark-guidelines': {
      id: '/legal/trademark-guidelines'
      path: '/legal/trademark-guidelines'
      fullPath: '/legal/trademark-guidelines'
      preLoaderRoute: typeof LegalTrademarkGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-use': {
      id: '/legal/terms-of-use'
      path: '/legal/terms-of-use'
      fullPath: '/legal/terms-of-use'
      preLoaderRoute: typeof LegalTermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$name/': {
      id: '/p/$name/'
      path: '/p/$name'
      fullPath: '/p/$name/'
      preLoaderRoute: typeof PNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/settings/': {
      id: '/notifications/settings/'
      path: '/settings'
      fullPath: '/notifications/settings/'
      preLoaderRoute: typeof NotificationsSettingsIndexRouteImport
      parentRoute: typeof NotificationsRouteRoute
    }
    '/debug/backend/': {
      id: '/debug/backend/'
      path: '/debug/backend'
      fullPath: '/debug/backend/'
      preLoaderRoute: typeof DebugBackendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$name/edit': {
      id: '/p/$name/edit'
      path: '/p/$name/edit'
      fullPath: '/p/$name/edit'
      preLoaderRoute: typeof PNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/backend/settings': {
      id: '/debug/backend/settings'
      path: '/debug/backend/settings'
      fullPath: '/debug/backend/settings'
      preLoaderRoute: typeof DebugBackendSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/channels/email/verify': {
      id: '/notifications/channels/email/verify'
      path: '/channels/email/verify'
      fullPath: '/notifications/channels/email/verify'
      preLoaderRoute: typeof NotificationsChannelsEmailVerifyRouteImport
      parentRoute: typeof NotificationsRouteRoute
    }
  }
}

interface NotificationsRouteRouteChildren {
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  NotificationsSettingsIndexRoute: typeof NotificationsSettingsIndexRoute
  NotificationsChannelsEmailVerifyRoute: typeof NotificationsChannelsEmailVerifyRoute
}

const NotificationsRouteRouteChildren: NotificationsRouteRouteChildren = {
  NotificationsIndexRoute: NotificationsIndexRoute,
  NotificationsSettingsIndexRoute: NotificationsSettingsIndexRoute,
  NotificationsChannelsEmailVerifyRoute: NotificationsChannelsEmailVerifyRoute,
}

const NotificationsRouteRouteWithChildren =
  NotificationsRouteRoute._addFileChildren(NotificationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificationsRouteRoute: NotificationsRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RegisterRoute: RegisterRoute,
  WalletRoute: WalletRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfUseRoute: LegalTermsOfUseRoute,
  LegalTrademarkGuidelinesRoute: LegalTrademarkGuidelinesRoute,
  PaymentAddRoute: PaymentAddRoute,
  PaymentListRoute: PaymentListRoute,
  AutoRenewalIndexRoute: AutoRenewalIndexRoute,
  DebugBackendSettingsRoute: DebugBackendSettingsRoute,
  PNameEditRoute: PNameEditRoute,
  DebugBackendIndexRoute: DebugBackendIndexRoute,
  PNameIndexRoute: PNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
