/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as AutoRenewalIndexRouteImport } from './routes/auto-renewal/index'
import { Route as PaymentListRouteImport } from './routes/payment/list'
import { Route as PaymentAddRouteImport } from './routes/payment/add'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications/settings'
import { Route as NotificationsAllRouteImport } from './routes/notifications/all'
import { Route as PNameIndexRouteImport } from './routes/p/$name/index'
import { Route as PNameEditRouteImport } from './routes/p/$name/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRenewalIndexRoute = AutoRenewalIndexRouteImport.update({
  id: '/auto-renewal/',
  path: '/auto-renewal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentListRoute = PaymentListRouteImport.update({
  id: '/payment/list',
  path: '/payment/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentAddRoute = PaymentAddRouteImport.update({
  id: '/payment/add',
  path: '/payment/add',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications/settings',
  path: '/notifications/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsAllRoute = NotificationsAllRouteImport.update({
  id: '/notifications/all',
  path: '/notifications/all',
  getParentRoute: () => rootRouteImport,
} as any)
const PNameIndexRoute = PNameIndexRouteImport.update({
  id: '/p/$name/',
  path: '/p/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const PNameEditRoute = PNameEditRouteImport.update({
  id: '/p/$name/edit',
  path: '/p/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/notifications/all': typeof NotificationsAllRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/auto-renewal': typeof AutoRenewalIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/p/$name/edit': typeof PNameEditRoute
  '/p/$name': typeof PNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/notifications/all': typeof NotificationsAllRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/auto-renewal': typeof AutoRenewalIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/p/$name/edit': typeof PNameEditRoute
  '/p/$name': typeof PNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/notifications/all': typeof NotificationsAllRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/auto-renewal/': typeof AutoRenewalIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/p/$name/edit': typeof PNameEditRoute
  '/p/$name/': typeof PNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/notifications/all'
    | '/notifications/settings'
    | '/payment/add'
    | '/payment/list'
    | '/auto-renewal'
    | '/notifications'
    | '/p/$name/edit'
    | '/p/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/notifications/all'
    | '/notifications/settings'
    | '/payment/add'
    | '/payment/list'
    | '/auto-renewal'
    | '/notifications'
    | '/p/$name/edit'
    | '/p/$name'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/notifications/all'
    | '/notifications/settings'
    | '/payment/add'
    | '/payment/list'
    | '/auto-renewal/'
    | '/notifications/'
    | '/p/$name/edit'
    | '/p/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  NotificationsAllRoute: typeof NotificationsAllRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  PaymentAddRoute: typeof PaymentAddRoute
  PaymentListRoute: typeof PaymentListRoute
  AutoRenewalIndexRoute: typeof AutoRenewalIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PNameEditRoute: typeof PNameEditRoute
  PNameIndexRoute: typeof PNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-renewal/': {
      id: '/auto-renewal/'
      path: '/auto-renewal'
      fullPath: '/auto-renewal'
      preLoaderRoute: typeof AutoRenewalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/list': {
      id: '/payment/list'
      path: '/payment/list'
      fullPath: '/payment/list'
      preLoaderRoute: typeof PaymentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/add': {
      id: '/payment/add'
      path: '/payment/add'
      fullPath: '/payment/add'
      preLoaderRoute: typeof PaymentAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/all': {
      id: '/notifications/all'
      path: '/notifications/all'
      fullPath: '/notifications/all'
      preLoaderRoute: typeof NotificationsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$name/': {
      id: '/p/$name/'
      path: '/p/$name'
      fullPath: '/p/$name'
      preLoaderRoute: typeof PNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$name/edit': {
      id: '/p/$name/edit'
      path: '/p/$name/edit'
      fullPath: '/p/$name/edit'
      preLoaderRoute: typeof PNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  NotificationsAllRoute: NotificationsAllRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  PaymentAddRoute: PaymentAddRoute,
  PaymentListRoute: PaymentListRoute,
  AutoRenewalIndexRoute: AutoRenewalIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PNameEditRoute: PNameEditRoute,
  PNameIndexRoute: PNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
