/// <reference types="vite/client" />

// Generated by wrangler using `pnpm cf-typegen`
interface ImportMetaEnv extends Readonly<Cloudflare.Env> {
  readonly VITE_ENABLE_DEBUG_FEATURES?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
