/// <reference types="vite/client" />

// Generated by wrangler using `pnpm cf-typegen`
interface ImportMetaEnv extends Readonly<Cloudflare.Env> {
  readonly VITE_ENABLE_DEBUG_FEATURES?: string
  /** Target network. Required: the build fails if it is unset or unknown. */
  readonly VITE_ENS_NETWORK?: string
  readonly VITE_SEPOLIA_RPC_URL?: string
  readonly VITE_SEPOLIA_RPC_URL_SERVER?: string
  readonly VITE_INDEXER_GRAPHQL_URL?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
