/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestImport } from './routes/test'
import { Route as RegisterImport } from './routes/register'
import { Route as IndexImport } from './routes/index'
import { Route as NotificationsIndexImport } from './routes/notifications/index'
import { Route as AutoRenewalIndexImport } from './routes/auto-renewal/index'
import { Route as PaymentAddImport } from './routes/payment/add'
import { Route as NotificationsSettingsImport } from './routes/notifications/settings'
import { Route as NotificationsAllImport } from './routes/notifications/all'

// Create/Update Routes

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsIndexRoute = NotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRoute,
} as any)

const AutoRenewalIndexRoute = AutoRenewalIndexImport.update({
  id: '/auto-renewal/',
  path: '/auto-renewal/',
  getParentRoute: () => rootRoute,
} as any)

const PaymentAddRoute = PaymentAddImport.update({
  id: '/payment/add',
  path: '/payment/add',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsSettingsRoute = NotificationsSettingsImport.update({
  id: '/notifications/settings',
  path: '/notifications/settings',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsAllRoute = NotificationsAllImport.update({
  id: '/notifications/all',
  path: '/notifications/all',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/notifications/all': {
      id: '/notifications/all'
      path: '/notifications/all'
      fullPath: '/notifications/all'
      preLoaderRoute: typeof NotificationsAllImport
      parentRoute: typeof rootRoute
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsImport
      parentRoute: typeof rootRoute
    }
    '/payment/add': {
      id: '/payment/add'
      path: '/payment/add'
      fullPath: '/payment/add'
      preLoaderRoute: typeof PaymentAddImport
      parentRoute: typeof rootRoute
    }
    '/auto-renewal/': {
      id: '/auto-renewal/'
      path: '/auto-renewal'
      fullPath: '/auto-renewal'
      preLoaderRoute: typeof AutoRenewalIndexImport
      parentRoute: typeof rootRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/notifications/all': typeof NotificationsAllRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/payment/add': typeof PaymentAddRoute
  '/auto-renewal': typeof AutoRenewalIndexRoute
  '/notifications': typeof NotificationsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/notifications/all': typeof NotificationsAllRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/payment/add': typeof PaymentAddRoute
  '/auto-renewal': typeof AutoRenewalIndexRoute
  '/notifications': typeof NotificationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
  '/notifications/all': typeof NotificationsAllRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/payment/add': typeof PaymentAddRoute
  '/auto-renewal/': typeof AutoRenewalIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/test'
    | '/notifications/all'
    | '/notifications/settings'
    | '/payment/add'
    | '/auto-renewal'
    | '/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/test'
    | '/notifications/all'
    | '/notifications/settings'
    | '/payment/add'
    | '/auto-renewal'
    | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/test'
    | '/notifications/all'
    | '/notifications/settings'
    | '/payment/add'
    | '/auto-renewal/'
    | '/notifications/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  TestRoute: typeof TestRoute
  NotificationsAllRoute: typeof NotificationsAllRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  PaymentAddRoute: typeof PaymentAddRoute
  AutoRenewalIndexRoute: typeof AutoRenewalIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  TestRoute: TestRoute,
  NotificationsAllRoute: NotificationsAllRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  PaymentAddRoute: PaymentAddRoute,
  AutoRenewalIndexRoute: AutoRenewalIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/register",
        "/test",
        "/notifications/all",
        "/notifications/settings",
        "/payment/add",
        "/auto-renewal/",
        "/notifications/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/notifications/all": {
      "filePath": "notifications/all.tsx"
    },
    "/notifications/settings": {
      "filePath": "notifications/settings.tsx"
    },
    "/payment/add": {
      "filePath": "payment/add.tsx"
    },
    "/auto-renewal/": {
      "filePath": "auto-renewal/index.tsx"
    },
    "/notifications/": {
      "filePath": "notifications/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
